package random

import "github.com/Oliverstalsy/egolifter/internal/domain"

var Exercises = []domain.Exercise{
	// Chest
	{ID: "c001", Name: "Barbell Bench Press", MuscleCategory: "Chest"},
	{ID: "c002", Name: "Incline Barbell Bench Press", MuscleCategory: "Chest"},
	{ID: "c003", Name: "Decline Barbell Bench Press", MuscleCategory: "Chest"},
	{ID: "c004", Name: "Dumbbell Bench Press", MuscleCategory: "Chest"},
	{ID: "c005", Name: "Incline Dumbbell Bench Press", MuscleCategory: "Chest"},
	{ID: "c006", Name: "Decline Dumbbell Bench Press", MuscleCategory: "Chest"},
	{ID: "c007", Name: "Dumbbell Flye", MuscleCategory: "Chest"},
	{ID: "c008", Name: "Incline Dumbbell Flye", MuscleCategory: "Chest"},
	{ID: "c009", Name: "Cable Crossover", MuscleCategory: "Chest"},
	{ID: "c010", Name: "Low Cable Flye", MuscleCategory: "Chest"},
	{ID: "c011", Name: "High Cable Flye", MuscleCategory: "Chest"},
	{ID: "c012", Name: "Chest Press Machine", MuscleCategory: "Chest"},
	{ID: "c013", Name: "Pec Deck Machine", MuscleCategory: "Chest"},
	{ID: "c014", Name: "Push-Up", MuscleCategory: "Chest"},
	{ID: "c015", Name: "Wide Grip Push-Up", MuscleCategory: "Chest"},
	{ID: "c016", Name: "Dips", MuscleCategory: "Chest"},
	{ID: "c017", Name: "Landmine Press", MuscleCategory: "Chest"},
	{ID: "c018", Name: "Svend Press", MuscleCategory: "Chest"},

	// Triceps
	{ID: "t001", Name: "Tricep Pushdown", MuscleCategory: "Triceps"},
	{ID: "t002", Name: "Rope Pushdown", MuscleCategory: "Triceps"},
	{ID: "t003", Name: "Overhead Tricep Extension", MuscleCategory: "Triceps"},
	{ID: "t004", Name: "Dumbbell Overhead Tricep Extension", MuscleCategory: "Triceps"},
	{ID: "t005", Name: "Skull Crusher", MuscleCategory: "Triceps"},
	{ID: "t006", Name: "Close Grip Bench Press", MuscleCategory: "Triceps"},
	{ID: "t007", Name: "Tricep Kickback", MuscleCategory: "Triceps"},
	{ID: "t008", Name: "Tricep Dips", MuscleCategory: "Triceps"},
	{ID: "t009", Name: "Diamond Push-Up", MuscleCategory: "Triceps"},
	{ID: "t010", Name: "Single Arm Cable Pushdown", MuscleCategory: "Triceps"},
	{ID: "t011", Name: "JM Press", MuscleCategory: "Triceps"},
	{ID: "t012", Name: "Tate Press", MuscleCategory: "Triceps"},
	{ID: "t013", Name: "Bench Dips", MuscleCategory: "Triceps"},

	// Biceps
	{ID: "b001", Name: "Barbell Curl", MuscleCategory: "Biceps"},
	{ID: "b002", Name: "Dumbbell Curl", MuscleCategory: "Biceps"},
	{ID: "b003", Name: "Hammer Curl", MuscleCategory: "Biceps"},
	{ID: "b004", Name: "Preacher Curl", MuscleCategory: "Biceps"},
	{ID: "b005", Name: "Incline Dumbbell Curl", MuscleCategory: "Biceps"},
	{ID: "b006", Name: "Concentration Curl", MuscleCategory: "Biceps"},
	{ID: "b007", Name: "Cable Curl", MuscleCategory: "Biceps"},
	{ID: "b008", Name: "EZ Bar Curl", MuscleCategory: "Biceps"},
	{ID: "b009", Name: "Reverse Curl", MuscleCategory: "Biceps"},
	{ID: "b010", Name: "Spider Curl", MuscleCategory: "Biceps"},
	{ID: "b011", Name: "Zottman Curl", MuscleCategory: "Biceps"},
	{ID: "b012", Name: "21s", MuscleCategory: "Biceps"},
	{ID: "b013", Name: "Cross Body Hammer Curl", MuscleCategory: "Biceps"},
	{ID: "b014", Name: "Chin-Up", MuscleCategory: "Biceps"},

	// Shoulders
	{ID: "s001", Name: "Overhead Press", MuscleCategory: "Shoulders"},
	{ID: "s002", Name: "Dumbbell Shoulder Press", MuscleCategory: "Shoulders"},
	{ID: "s003", Name: "Arnold Press", MuscleCategory: "Shoulders"},
	{ID: "s004", Name: "Lateral Raise", MuscleCategory: "Shoulders"},
	{ID: "s005", Name: "Cable Lateral Raise", MuscleCategory: "Shoulders"},
	{ID: "s006", Name: "Front Raise", MuscleCategory: "Shoulders"},
	{ID: "s007", Name: "Rear Delt Flye", MuscleCategory: "Shoulders"},
	{ID: "s008", Name: "Face Pull", MuscleCategory: "Shoulders"},
	{ID: "s009", Name: "Upright Row", MuscleCategory: "Shoulders"},
	{ID: "s010", Name: "Machine Shoulder Press", MuscleCategory: "Shoulders"},
	{ID: "s011", Name: "Seated Dumbbell Press", MuscleCategory: "Shoulders"},
	{ID: "s012", Name: "Push Press", MuscleCategory: "Shoulders"},
	{ID: "s013", Name: "Landmine Lateral Raise", MuscleCategory: "Shoulders"},
	{ID: "s014", Name: "Cable Front Raise", MuscleCategory: "Shoulders"},
	{ID: "s015", Name: "Prone Rear Delt Raise", MuscleCategory: "Shoulders"},
	{ID: "s016", Name: "Shrugs", MuscleCategory: "Shoulders"},

	// Back
	{ID: "bk01", Name: "Deadlift", MuscleCategory: "Back"},
	{ID: "bk02", Name: "Pull-Up", MuscleCategory: "Back"},
	{ID: "bk03", Name: "Lat Pulldown", MuscleCategory: "Back"},
	{ID: "bk04", Name: "Barbell Row", MuscleCategory: "Back"},
	{ID: "bk05", Name: "Dumbbell Row", MuscleCategory: "Back"},
	{ID: "bk06", Name: "Seated Cable Row", MuscleCategory: "Back"},
	{ID: "bk07", Name: "T-Bar Row", MuscleCategory: "Back"},
	{ID: "bk08", Name: "Chest Supported Row", MuscleCategory: "Back"},
	{ID: "bk09", Name: "Straight Arm Pulldown", MuscleCategory: "Back"},
	{ID: "bk10", Name: "Single Arm Cable Row", MuscleCategory: "Back"},
	{ID: "bk11", Name: "Rack Pull", MuscleCategory: "Back"},
	{ID: "bk12", Name: "Romanian Deadlift", MuscleCategory: "Back"},
	{ID: "bk13", Name: "Good Morning", MuscleCategory: "Back"},
	{ID: "bk14", Name: "Hyperextension", MuscleCategory: "Back"},
	{ID: "bk15", Name: "Meadows Row", MuscleCategory: "Back"},
	{ID: "bk16", Name: "Wide Grip Lat Pulldown", MuscleCategory: "Back"},
	{ID: "bk17", Name: "Close Grip Lat Pulldown", MuscleCategory: "Back"},
	{ID: "bk18", Name: "Inverted Row", MuscleCategory: "Back"},
	{ID: "bk19", Name: "Pendlay Row", MuscleCategory: "Back"},

	// Legs
	{ID: "l001", Name: "Barbell Squat", MuscleCategory: "Legs"},
	{ID: "l002", Name: "Front Squat", MuscleCategory: "Legs"},
	{ID: "l003", Name: "Hack Squat", MuscleCategory: "Legs"},
	{ID: "l004", Name: "Leg Press", MuscleCategory: "Legs"},
	{ID: "l005", Name: "Leg Extension", MuscleCategory: "Legs"},
	{ID: "l006", Name: "Leg Curl", MuscleCategory: "Legs"},
	{ID: "l007", Name: "Seated Leg Curl", MuscleCategory: "Legs"},
	{ID: "l008", Name: "Romanian Deadlift", MuscleCategory: "Legs"},
	{ID: "l009", Name: "Stiff Leg Deadlift", MuscleCategory: "Legs"},
	{ID: "l010", Name: "Sumo Deadlift", MuscleCategory: "Legs"},
	{ID: "l011", Name: "Bulgarian Split Squat", MuscleCategory: "Legs"},
	{ID: "l012", Name: "Lunge", MuscleCategory: "Legs"},
	{ID: "l013", Name: "Walking Lunge", MuscleCategory: "Legs"},
	{ID: "l014", Name: "Step Up", MuscleCategory: "Legs"},
	{ID: "l015", Name: "Goblet Squat", MuscleCategory: "Legs"},
	{ID: "l016", Name: "Standing Calf Raise", MuscleCategory: "Legs"},
	{ID: "l017", Name: "Seated Calf Raise", MuscleCategory: "Legs"},
	{ID: "l018", Name: "Hip Thrust", MuscleCategory: "Legs"},
	{ID: "l019", Name: "Glute Bridge", MuscleCategory: "Legs"},
	{ID: "l020", Name: "Cable Kickback", MuscleCategory: "Legs"},
	{ID: "l021", Name: "Abductor Machine", MuscleCategory: "Legs"},
	{ID: "l022", Name: "Adductor Machine", MuscleCategory: "Legs"},
	{ID: "l023", Name: "Box Squat", MuscleCategory: "Legs"},
	{ID: "l024", Name: "Sissy Squat", MuscleCategory: "Legs"},
	{ID: "l025", Name: "Nordic Curl", MuscleCategory: "Legs"},
}
